### ISSUE TITLE
libcudnn.so.6 not found

### ISSUE THREAD

**Issue by takabow** [takabow/cdsw-demo-env#25]
After creating python3 and tensorflow-gpu env, I got  the following error when I `import tensorflow`.

```
import tensorflow as tf
ImportError: Traceback (most recent call last):
  File "/home/cdsw/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/cdsw/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/cdsw/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/local/lib/python3.6/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/local/lib/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcudnn.so.6: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.
```

**Comment by takabow** [comment]
https://www.cloudera.com/documentation/data-science-workbench/latest/topics/cdsw_gpu.html

I created a custom CUDA-capable Engine Image in accordance with the current latest document of CDSW 1.1.1
It seems like the wrong(old) version of cuddn. 

```
ENV CUDNN_VERSION 5.1.10
LABEL com.nvidia.cudnn.version="${CUDNN_VERSION}"

RUN apt-get update && apt-get install -y --no-install-recommends \
            libcudnn5=$CUDNN_VERSION-1+cuda8.0 && \
    rm -rf /var/lib/apt/lists/*
```

**Comment by takabow** [comment]
route cause? https://github.com/tensorflow/tensorboard/releases/tag/0.1.5
